development:
  adapter: postgresql
  database: practice_space_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: practice_space_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: practice_space_production
  pool: 5
  timeout: 5000
